### ISSUE TITLE
Handle circular references in ArrayContractParameter.

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#160]
Title. Should probably fail fast when it sees a reference it's already seen. See ArrayContractParameter.js

**Comment by davemneo** [comment]
Clarification exchanged via email:
in relation to ArrayLikeStackItem.toContractParameter. You should pass in a set of seen references, check if this is already in the seen set, if it is, throw an error, otherwise copy the seen set and add this to it. Similarly for MapStackItem, and any other stack items that could have circular references (i.e. they call toContractParameter recursively)
https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-node-vm/src/stackItem/ArrayLikeStackItem.js

**Comment by davemneo** [comment]
Submitted pull request for peer-review so we may discuss this possible solution if this path is reasonable:
https://github.com/neo-one-suite/neo-one/pull/187

**Comment by davemneo** [comment]
see pull request: https://github.com/neo-one-suite/neo-one/pull/187
