### ISSUE TITLE
Playground's NEO tracker instance doesn't work

### ISSUE THREAD

**Issue by spencercorwin** [neo-one-suite/neo-one#1748]
### Description

The playground's local instance of NEO tracker doesn't seem to work.

### Steps to Reproduce

1. Go to the playground
2. `yarn neo-one build`
3. `yarn start`
4. Press a button like `console.log` on the homepage and see the iframe produce a link to the transaction on NEO tracker
5. Click the link and see that the NEO tracker instance is not up

**Expected behavior:** The link to go to a local NEO tracker instance

**Actual behavior:** Nothing is up

**Reproduces how often:** 100%

### Additional Information

None.

**Comment by dicarlo2** [comment]
I think we should do the following:

1. Fully open-source neotracker and eliminate the private repo. Then we can run it on the neotracker redesign infra.
2. Eliminate @neo-one/monitor since it doesn't exist anymore.
3. Re-integrate it with the neo-one cli <- I've already done this on a local branch, just need 2/ to be done.
