### ISSUE TITLE
Automate data backups

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#710]
Setup a public google cloud bucket for storing the backups. Setup a circleci cron job with the node image that downloads the latest backup, synchronizes the blockchain to the current time, re-uploads the backup, cleans up 1 backup (we should keep say 7 days worth) and also points/copies the latest file to a file named with the suffix `latest`. It should also create a chain dump file. Pointers:

 - https://github.com/neo-one-suite/neo-one/tree/master/packages/neo-one-node-data-backup - contains the code for backing up and restoring from google cloud.
 - https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-node/src/fullNode%24.ts#L226 example usage in the node for backing up on a schedule.
 - https://github.com/neo-one-suite/neo-one/tree/master/packages/neo-one-node-offline contains the code for dumping a chain file.

We should just go ahead and use the same entry point file (https://zube.io/neo-one/neo-one/c/714) and simply add additional configuration that controls the "mode" we're running in - i.e. the normal continuous mode or the above mode where we shutdown after finishing the work we need to complete.

**Comment by danwbyrne** [comment]
When it is restoring it will just sit there with no output. Would be nice to know it isn't just hanging.

**Comment by danwbyrne** [comment]
breaking: temporarily disabling `@neo-one/node-data-backup/src/provider/extract.ts` in `@neo-one/node-data-backup/src/provider/GCloudProvider.ts` and using `tar.extract(...)` on each downloaded backup instead of using the `fileStream` approach. This means there is no `Throttle` on the bytes written per second by the extraction method, `writeBytesPerSecond` will be unused.
